# Configurable Settings
# ---------------------
# These settings will change on a per-site
title: Linaro Simply Static Theme
description: > # this means to ignore newlines until "baseurl:"
  A lightweight foundation css framework Jekyll theme.
tagline: A lightweight foundation css framework Jekyll theme.
email: contact@linaro.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:5000" # the base hostname & protocol for your site
google_analytics: UA-XXXXXXXXXX-4
favicon: /assets/images/favicon.png
# breadcrumb_image: /assets/images/content/breadcrumb.png
# Social Media Links
twitter_username: LinaroOrg
facebook_username: LinaroOrg
linkedin_username: false
youtube_username: LinaroOrg
github_username: Linaro
social_share_image: /assets/images/social-media-image.png
disqus_shortname: linaro
# Blog Settings
blog:
  filler_element: collection_display_filler_element.html
  avatar_placeholder: /assets/images/avatar-placeholder.jpg
# GitHub Edit Settings
github_edit:
  enabled: true
  repo: "https://github.com/96boards/website"
# Main Jekyll Settings
# --------------------
# These settings will, usually, remain the same
# for each site
include: ["_test_site", "_pages"] # Include the site content
highlighter: rouge # Default syntax highlighter
permalink: /:categories/:title/ # Default Post permalink
markdown: kramdown # Default Markdown Processor
# Jekyll Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate-v2
  - japr
  - jekyll-tidy
  - jekyll_amp
  - jekyll-toc
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-toc
  - jekyll-optional-front-matter
  - jekyll-readme-index
# Jekyll Collections
collections:
  authors:
    output: true
    permalink: /author/:name/
    layout: page
  # Test the products config
  products:
    output: true
    permalink: /products/:name/
    layout: product
  # Test the products config
  documentation:
    output: true
    layout: documentation
# Jekyll Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      type: posts
    values:
      layout: "post"
      is_post: true
  - scope:
      type: products
    values:
      layout: "product"
      is_post: true
      github_edit:
        enabled: true
        repo: https://github.com/96boards/documentation
        strip_from_path: _products/
  - scope:
      type: documentation
    values:
      layout: "documentation"
      output: true
      permalink: "/documentation/:path/"
      strip_title: true
      toc: true
      tab_nav: true
# Jekyll SASS Config
sass:
  sass_dir: _sass
  style: compressed
# Excluded Files
# these files are excluded from
# processing when running a jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - .jekyll-cache
  - _site
  - package.json
  - node_modules/*
  - gulpfile.js
  - .jekyll-cache
  - README.md
  - LICENSE.txt
  - "*.gemspec"
  - "*-lock.json"
# Jekyll Plugin Settings
# ----------------------
# These settings are used to initialise the
# jekyll plugins that we're using.
# ----------------------
# jekyll_picture_tag
picture:
  nomarkdown: false
  source: "assets/images"
  output: "assets/images"
  relative_url: false
# jekyll_paginate_v2
pagination:
  # Default pagination path for Jekyll Posts
  # For other permalinks set in the front matter of the post index page
  permalink: /:num/
  # Enabled or not?
  enabled: true
  # Home many posts to display by default
  per_page: 9
  # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
  trail:
    before: 2
    after: 2
  # Reverse the order of paginated pages
  sort_reverse: true
  # Field to sort posts by when paginating
  sort_field: "date"
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
# japr
# A Jekyll asset pipeline
# This is being used for the concatenation/compression of JS
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false
  # strip_from_path: _documentation
# jekyll_amp
# Accelerated Mobile pages support
ampdir: /amp
amp: false
# jekyll_toc
toc:
  # Default is "section-nav":
  list_class: doc_nav vertical menu accordion-menu
  # Default is no class for sublists:
  sublist_class: doc_nav__sublist menu vertical nested
  # Default is "toc-entry":
  item_class: doc_nav_item
  # Default is "toc-":
  item_prefix: doc_nav_toc_
  ordered: true
# jekyll-relative-links
relative_links:
  enabled: true
  collections: false
# jekyll-titles-from-headings
titles_from_headings:
  enabled: true
  strip_title: false
  collections: true
# jekyll-optional-front-matter
optional_front_matter:
  remove_originals: true
  enabled: true
# jekyll-readme-index
readme_index:
  remove_originals: true
  with_frontmatter: true
# jekyll-tidy
jekyll_tidy:
  # Toggle compression of HTML
  compress_html: true
  # JS Path added to exclude to stop errors.
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
