title: Linaro Simply Static Theme
email: kyle.kirkby@linaro.org
description: > # this means to ignore newlines until "baseurl:"
  A lightweight foundation css framework Jekyll theme.
tagline:  A lightweight foundation css framework Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
highlighter: rouge
google_analytics: UA-XXXXXXXXXX-4
# Default Post permalink
permalink: /:categories/:title/
# Default Markdown Processor
markdown: kramdown
favicon: /assets/images/favicon.png
# Jekyll Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate-v2
  - japr
  # - jekyll_amp
collections:
  authors:
    output: true
    permalink: /author/:name/
    layout: page
  # Test the products config
  products:
    output: true
    permalink: /product/:name/
    layout: product
# SASS Config
sass:
  sass_dir: _sass
  style: compressed
# Exclude Array - these files are excluded from
# processing when running a jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - .jekyll-cache
  - _site
  - package.json
  - node_modules/*
  - gulpfile.js
  - .jekyll-cache
  - README.md
  - LICENSE.txt
  - "*.gemspec"
  - "*-lock.json"
picture:
  nomarkdown: false
  source: "assets/images"
  output: "assets/images"
  relative_url: false
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  - scope:
      type: posts # an empty string here means all files in the project
    values:
      layout: "post"
      is_post: true
      image:
        path: /assets/images/placeholder.jpg
  - scope:
      type: products # an empty string here means all files in the project
    values:
      layout: "product"
      is_post: true
      github_edit:
        enabled: true
        repo: https://github.com/96boards/documentation
        strip_from_path: _products/
# Include the site content
include: ["_test_site", "_pages"]
# Social Media Links
twitter_username: LinaroOrg
facebook_username: LinaroOrg
linkedin_username: false
youtube_username: LinaroOrg
github_username: Linaro
social_share_image: /assets/images/social-media-image.png
disqus_shortname: linaro
# Jekyll Pagination V2 Configuration
pagination:
  # Default pagination path for Jekyll Posts
  # For other permalinks set in the front matter of the post index page
  permalink: /:num/
  # Enabled or not?
  enabled: true
  # Home many posts to display by default
  per_page: 9
  # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
  trail:
    before: 2
    after: 2
  # Reverse the order of paginated pages
  sort_reverse: true
  # Field to sort posts by when paginating
  sort_field: "date"
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
#Test config
breadcrumb_image: /assets/images/content/breadcrumb.png
# JAPR asset pipeline
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false
blog:
  filler_element: collection_display_filler_element.html
  avatar_placeholder: /assets/images/avatar-placeholder.jpg
github_edit:
  enabled: true
  repo: "https://github.com/96boards/website"
  # strip_from_path: _documentation
# jekyll_amp config
ampdir: /amp
amp: false
