title: Linaro Simply Static Theme
email: kyle.kirkby@linaro.org
description: > # this means to ignore newlines until "baseurl:"
  A lightweight foundation css framework Jekyll theme.
tagline:  A lightweight foundation css framework Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
highlighter: rouge
google_analytics: UA-XXXXXXXXXX-4
# Default Post permalink
permalink: /:categories/:title/
# Default Markdown Processor
markdown: kramdown
favicon: /assets/images/favicon.png
# Jekyll Plugins
plugins:
  - jekyll-4-picture-tag
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-include-cache
# SASS Config
sass:
  sass_dir: _sass
  style: compressed
# Exclude Array - these files are excluded from
# processing when running a jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - .jekyll-cache
  - _site
  - package.json
  - node_modules/*
  - gulpfile.js
  - .jekyll-cache
  - README.md
  - LICENSE.txt
  - "*.gemspec"
  - "*-lock.json"
picture:
  nomarkdown: false
  source: "assets/images"
  output: "assets/images"
  relative_url: false
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      type: posts # an empty string here means all files in the project
    values:
      layout: "post"
      is_post: true
      image:
        path: /assets/images/placeholder.jpg
# Include the site content
include: ["_test_site", "_pages"]
