baseurl: "/themes/lsst" # the subpath of your site, e.g. /blog
url: "https://static.linaro.org" # the base hostname & protocol for your site
# JAPR asset pipeline
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: themes/lsst/assets
  gzip: false
