title: Linaro Simply Static Theme
description: > # this means to ignore newlines until "baseurl:"
  A lightweight foundation css framework Jekyll theme.
tagline:  A lightweight foundation css framework Jekyll theme.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://localhost:4001" # the base hostname & protocol for your site

google_analytics: UA-XXXXXXXXXX-4
highlighter: rouge
# Default Post permalink
permalink: /:categories/:title/
# Default Markdown Processor
markdown: kramdown
favicon: /assets/images/favicon.png
# Jekyll Plugins
plugins:
  - jekyll_picture_tag
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate-v2
  - japr
  - jekyll_amp
  - jekyll-toc
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-optional-front-matter
collections:
  authors:
    output: true
    permalink: /author/:name/
    layout: page
  # Test the products config
  products:
    output: true
    permalink: /product/:name/
    layout: product
  # Test the products config
  documentation:
    output: true
    layout: documentation
# SASS Config
sass:
  sass_dir: _sass
  style: compressed
# Exclude Array - these files are excluded from
# processing when running a jekyll build
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - .jekyll-cache
  - _site
  - package.json
  - node_modules/*
  - gulpfile.js
  - .jekyll-cache
  - README.md
  - LICENSE.txt
  - "*.gemspec"
  - "*-lock.json"
picture:
  nomarkdown: false
  source: "assets/images"
  output: "assets/images"
  relative_url: false
defaults:
  - scope:
      type: posts # an empty string here means all files in the project
    values:
      layout: "post"
      is_post: true
  - scope:
      type: products # an empty string here means all files in the project
    values:
      layout: "product"
      is_post: true
      github_edit:
        enabled: true
        repo: https://github.com/96boards/documentation
        strip_from_path: _products/
  - scope:
      type: documentation # an empty string here means all files in the project
    values:
      layout: "documentation"
      output: true
      permalink: "/documentation/:path/"
      strip_title: true
      toc: true
# Include the site content
include: ["_test_site", "_pages"]
# Social Media Links
twitter_username: LinaroOrg
facebook_username: LinaroOrg
linkedin_username: false
youtube_username: LinaroOrg
github_username: Linaro
social_share_image: /assets/images/social-media-image.png
disqus_shortname: linaro
# Jekyll Pagination V2 Configuration
pagination:
  # Default pagination path for Jekyll Posts
  # For other permalinks set in the front matter of the post index page
  permalink: /:num/
  # Enabled or not?
  enabled: true
  # Home many posts to display by default
  per_page: 9
  # Number of pages to show either side of the current page i.e - 1, 2, {3}, 4, 5
  trail:
    before: 2
    after: 2
  # Reverse the order of paginated pages
  sort_reverse: true
  # Field to sort posts by when paginating
  sort_field: "date"
# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false
#Test config
breadcrumb_image: /assets/images/content/breadcrumb.png
# JAPR asset pipeline
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  gzip: false
blog:
  filler_element: collection_display_filler_element.html
  avatar_placeholder: /assets/images/avatar-placeholder.jpg
github_edit:
  enabled: true
  repo: "https://github.com/96boards/website"
  # strip_from_path: _documentation
# jekyll_amp config
ampdir: /amp
amp: false
# Jekyll-toc config
toc:
  # Default is "section-nav":
  list_class: doc_nav vertical menu accordion-menu
  # Default is no class for sublists:
  sublist_class: doc_nav__sublist menu vertical nested
  # Default is "toc-entry":
  item_class: doc_nav_item
  # Default is "toc-":
  item_prefix: doc_nav_toc_
  ordered: true
# jekyll-relative-links config
relative_links:
  enabled:     true
  collections: false
# jekyll-titles-from-headings config
titles_from_headings:
  enabled:     true
  strip_title: false
  collections: true
# jekyll-optional-front-matter config
optional_front_matter:
  remove_originals: true
  enabled: true
